- hosts: all
  become: true
  vars_files:
    - vars/vault.yml
  roles:
    - role: infra.ado.rhel_sat_reg
      vars:
        rhel_sat_reg_org_admin_account: "admin"
        rhel_sat_reg_org_admin_account_password: "{{ vault_sat_password }}"
        rhel_sat_reg_activation_key_name: "rhel-9"
        rhel_sat_reg_satellite_org_name: "Lab"
        rhel_sat_reg_satellite_host: "http://sat.server.lab"
        rhel_sat_reg_action: "register"  # or "deregister"
        rhel_sat_reg_insecure: true
        rhel_sat_reg_validate_certs: false  